import { City } from '@/types';

export const cities: City[] = [
  // Headquarters
  { name: 'Marlborough', slug: 'marlborough', county: 'Middlesex', state: 'MA', zip: '01752', distance: 0, isHeadquarters: true, description: 'Our headquarters location serving the heart of Massachusetts.' },

  // Middlesex County (15-20 min radius)
  { name: 'Framingham', slug: 'framingham', county: 'Middlesex', state: 'MA', zip: '01701', distance: 5 },
  { name: 'Natick', slug: 'natick', county: 'Middlesex', state: 'MA', zip: '01760', distance: 6 },
  { name: 'Hudson', slug: 'hudson', county: 'Middlesex', state: 'MA', zip: '01749', distance: 4 },
  { name: 'Sudbury', slug: 'sudbury', county: 'Middlesex', state: 'MA', zip: '01776', distance: 7 },
  { name: 'Ashland', slug: 'ashland', county: 'Middlesex', state: 'MA', zip: '01721', distance: 9 },
  { name: 'Hopkinton', slug: 'hopkinton', county: 'Middlesex', state: 'MA', zip: '01748', distance: 11 },
  { name: 'Holliston', slug: 'holliston', county: 'Middlesex', state: 'MA', zip: '01746', distance: 12 },
  { name: 'Sherborn', slug: 'sherborn', county: 'Middlesex', state: 'MA', zip: '01770', distance: 13 },
  { name: 'Maynard', slug: 'maynard', county: 'Middlesex', state: 'MA', zip: '01754', distance: 9 },
  { name: 'Stow', slug: 'stow', county: 'Middlesex', state: 'MA', zip: '01775', distance: 10 },
  { name: 'Acton', slug: 'acton', county: 'Middlesex', state: 'MA', zip: '01720', distance: 12 },
  { name: 'Concord', slug: 'concord', county: 'Middlesex', state: 'MA', zip: '01742', distance: 14 },
  { name: 'Lincoln', slug: 'lincoln', county: 'Middlesex', state: 'MA', zip: '01773', distance: 13 },
  { name: 'Boxborough', slug: 'boxborough', county: 'Middlesex', state: 'MA', zip: '01719', distance: 11 },
  { name: 'Littleton', slug: 'littleton', county: 'Middlesex', state: 'MA', zip: '01460', distance: 13 },
  { name: 'Groton', slug: 'groton', county: 'Middlesex', state: 'MA', zip: '01450', distance: 16 },
  { name: 'Ayer', slug: 'ayer', county: 'Middlesex', state: 'MA', zip: '01432', distance: 15 },
  { name: 'Wayland', slug: 'wayland', county: 'Middlesex', state: 'MA', zip: '01778', distance: 10 },
  { name: 'Weston', slug: 'weston', county: 'Middlesex', state: 'MA', zip: '02493', distance: 11 },

  // Worcester County
  { name: 'Southborough', slug: 'southborough', county: 'Worcester', state: 'MA', zip: '01772', distance: 4 },
  { name: 'Northborough', slug: 'northborough', county: 'Worcester', state: 'MA', zip: '01532', distance: 6 },
  { name: 'Berlin', slug: 'berlin', county: 'Worcester', state: 'MA', zip: '01503', distance: 5 },
  { name: 'Bolton', slug: 'bolton', county: 'Worcester', state: 'MA', zip: '01740', distance: 8 },
  { name: 'Westborough', slug: 'westborough', county: 'Worcester', state: 'MA', zip: '01581', distance: 7 },
  { name: 'Shrewsbury', slug: 'shrewsbury', county: 'Worcester', state: 'MA', zip: '01545', distance: 9 },
  { name: 'Worcester', slug: 'worcester', county: 'Worcester', state: 'MA', zip: '01608', distance: 12 },
  { name: 'Grafton', slug: 'grafton', county: 'Worcester', state: 'MA', zip: '01519', distance: 11 },
  { name: 'Millbury', slug: 'millbury', county: 'Worcester', state: 'MA', zip: '01527', distance: 12 },
  { name: 'Auburn', slug: 'auburn', county: 'Worcester', state: 'MA', zip: '01501', distance: 13 },
  { name: 'Boylston', slug: 'boylston', county: 'Worcester', state: 'MA', zip: '01505', distance: 10 },
  { name: 'Clinton', slug: 'clinton', county: 'Worcester', state: 'MA', zip: '01510', distance: 10 },
  { name: 'Lancaster', slug: 'lancaster', county: 'Worcester', state: 'MA', zip: '01523', distance: 12 },
  { name: 'Sterling', slug: 'sterling', county: 'Worcester', state: 'MA', zip: '01564', distance: 11 },
  { name: 'West Boylston', slug: 'west-boylston', county: 'Worcester', state: 'MA', zip: '01583', distance: 10 },
  { name: 'Holden', slug: 'holden', county: 'Worcester', state: 'MA', zip: '01520', distance: 12 },
  { name: 'Harvard', slug: 'harvard', county: 'Worcester', state: 'MA', zip: '01451', distance: 14 },
  { name: 'Rutland', slug: 'rutland', county: 'Worcester', state: 'MA', zip: '01543', distance: 18 },
  { name: 'Paxton', slug: 'paxton', county: 'Worcester', state: 'MA', zip: '01612', distance: 14 },
  { name: 'Leicester', slug: 'leicester', county: 'Worcester', state: 'MA', zip: '01524', distance: 16 },
  { name: 'Spencer', slug: 'spencer', county: 'Worcester', state: 'MA', zip: '01562', distance: 20 },
  { name: 'Charlton', slug: 'charlton', county: 'Worcester', state: 'MA', zip: '01507', distance: 21 },
  { name: 'Oxford', slug: 'oxford', county: 'Worcester', state: 'MA', zip: '01540', distance: 22 },
  { name: 'Webster', slug: 'webster', county: 'Worcester', state: 'MA', zip: '01570', distance: 24 },
  { name: 'Sutton', slug: 'sutton', county: 'Worcester', state: 'MA', zip: '01590', distance: 19 },
  { name: 'Douglas', slug: 'douglas', county: 'Worcester', state: 'MA', zip: '01516', distance: 25 },
  { name: 'Uxbridge', slug: 'uxbridge', county: 'Worcester', state: 'MA', zip: '01569', distance: 24 },
  { name: 'Milford', slug: 'milford', county: 'Worcester', state: 'MA', zip: '01757', distance: 14 },
  { name: 'Hopedale', slug: 'hopedale', county: 'Worcester', state: 'MA', zip: '01747', distance: 17 },
  { name: 'Mendon', slug: 'mendon', county: 'Worcester', state: 'MA', zip: '01756', distance: 16 },
  { name: 'Upton', slug: 'upton', county: 'Worcester', state: 'MA', zip: '01568', distance: 15 },
  { name: 'Blackstone', slug: 'blackstone', county: 'Worcester', state: 'MA', zip: '01504', distance: 22 },
  { name: 'Millville', slug: 'millville', county: 'Worcester', state: 'MA', zip: '01529', distance: 23 },
  { name: 'Northbridge', slug: 'northbridge', county: 'Worcester', state: 'MA', zip: '01534', distance: 20 },
  { name: 'Whitinsville', slug: 'whitinsville', county: 'Worcester', state: 'MA', zip: '01588', distance: 19 },

  // Norfolk County
  { name: 'Wellesley', slug: 'wellesley', county: 'Norfolk', state: 'MA', zip: '02481', distance: 14 },
  { name: 'Medway', slug: 'medway', county: 'Norfolk', state: 'MA', zip: '02053', distance: 13 },
  { name: 'Millis', slug: 'millis', county: 'Norfolk', state: 'MA', zip: '02054', distance: 14 },
  { name: 'Dover', slug: 'dover', county: 'Norfolk', state: 'MA', zip: '02030', distance: 15 },
  { name: 'Needham', slug: 'needham', county: 'Norfolk', state: 'MA', zip: '02492', distance: 13 },
  { name: 'Dedham', slug: 'dedham', county: 'Norfolk', state: 'MA', zip: '02026', distance: 18 },
  { name: 'Norwood', slug: 'norwood', county: 'Norfolk', state: 'MA', zip: '02062', distance: 17 },
  { name: 'Westwood', slug: 'westwood', county: 'Norfolk', state: 'MA', zip: '02090', distance: 16 },
  { name: 'Canton', slug: 'canton', county: 'Norfolk', state: 'MA', zip: '02021', distance: 19 },
  { name: 'Sharon', slug: 'sharon', county: 'Norfolk', state: 'MA', zip: '02067', distance: 20 },
  { name: 'Foxborough', slug: 'foxborough', county: 'Norfolk', state: 'MA', zip: '02035', distance: 21 },
  { name: 'Franklin', slug: 'franklin', county: 'Norfolk', state: 'MA', zip: '02038', distance: 16 },
  { name: 'Bellingham', slug: 'bellingham', county: 'Norfolk', state: 'MA', zip: '02019', distance: 18 },
  { name: 'Brookline', slug: 'brookline', county: 'Norfolk', state: 'MA', zip: '02445', distance: 19 },
  { name: 'Milton', slug: 'milton', county: 'Norfolk', state: 'MA', zip: '02186', distance: 22 },
  { name: 'Quincy', slug: 'quincy', county: 'Norfolk', state: 'MA', zip: '02169', distance: 24 },
  { name: 'Braintree', slug: 'braintree', county: 'Norfolk', state: 'MA', zip: '02184', distance: 23 },
  { name: 'Randolph', slug: 'randolph', county: 'Norfolk', state: 'MA', zip: '02368', distance: 24 },
  { name: 'Holbrook', slug: 'holbrook', county: 'Norfolk', state: 'MA', zip: '02343', distance: 25 },

  // Metro Middlesex Extended
  { name: 'Newton', slug: 'newton', county: 'Middlesex', state: 'MA', zip: '02458', distance: 16 },
  { name: 'Waltham', slug: 'waltham', county: 'Middlesex', state: 'MA', zip: '02451', distance: 14 },
  { name: 'Watertown', slug: 'watertown', county: 'Middlesex', state: 'MA', zip: '02472', distance: 17 },
  { name: 'Belmont', slug: 'belmont', county: 'Middlesex', state: 'MA', zip: '02478', distance: 18 },
  { name: 'Arlington', slug: 'arlington', county: 'Middlesex', state: 'MA', zip: '02474', distance: 19 },
  { name: 'Lexington', slug: 'lexington', county: 'Middlesex', state: 'MA', zip: '02420', distance: 16 },
  { name: 'Bedford', slug: 'bedford', county: 'Middlesex', state: 'MA', zip: '01730', distance: 17 },
  { name: 'Burlington', slug: 'burlington', county: 'Middlesex', state: 'MA', zip: '01803', distance: 16 },
  { name: 'Woburn', slug: 'woburn', county: 'Middlesex', state: 'MA', zip: '01801', distance: 18 },
  { name: 'Winchester', slug: 'winchester', county: 'Middlesex', state: 'MA', zip: '01890', distance: 19 },
  { name: 'Medford', slug: 'medford', county: 'Middlesex', state: 'MA', zip: '02155', distance: 20 },
  { name: 'Somerville', slug: 'somerville', county: 'Middlesex', state: 'MA', zip: '02143', distance: 21 },
  { name: 'Cambridge', slug: 'cambridge', county: 'Middlesex', state: 'MA', zip: '02138', distance: 20 },
  { name: 'Chelmsford', slug: 'chelmsford', county: 'Middlesex', state: 'MA', zip: '01824', distance: 20 },
  { name: 'Billerica', slug: 'billerica', county: 'Middlesex', state: 'MA', zip: '01821', distance: 19 },
  { name: 'Tewksbury', slug: 'tewksbury', county: 'Middlesex', state: 'MA', zip: '01876', distance: 21 },
  { name: 'Wilmington', slug: 'wilmington', county: 'Middlesex', state: 'MA', zip: '01887', distance: 20 },
  { name: 'Reading', slug: 'reading', county: 'Middlesex', state: 'MA', zip: '01867', distance: 20 },
  { name: 'North Reading', slug: 'north-reading', county: 'Middlesex', state: 'MA', zip: '01864', distance: 21 },
  { name: 'Westford', slug: 'westford', county: 'Middlesex', state: 'MA', zip: '01886', distance: 21 },
  { name: 'Carlisle', slug: 'carlisle', county: 'Middlesex', state: 'MA', zip: '01741', distance: 18 },
  { name: 'Dunstable', slug: 'dunstable', county: 'Middlesex', state: 'MA', zip: '01827', distance: 23 },

  // Essex County - Expanded
  { name: 'Andover', slug: 'andover', county: 'Essex', state: 'MA', zip: '01810', distance: 24 },
  { name: 'North Andover', slug: 'north-andover', county: 'Essex', state: 'MA', zip: '01845', distance: 26 },
  { name: 'Lawrence', slug: 'lawrence', county: 'Essex', state: 'MA', zip: '01840', distance: 28 },
  { name: 'Methuen', slug: 'methuen', county: 'Essex', state: 'MA', zip: '01844', distance: 30 },
  { name: 'Haverhill', slug: 'haverhill', county: 'Essex', state: 'MA', zip: '01830', distance: 35 },
  { name: 'Salem', slug: 'salem', county: 'Essex', state: 'MA', zip: '01970', distance: 30 },
  { name: 'Peabody', slug: 'peabody', county: 'Essex', state: 'MA', zip: '01960', distance: 26 },
  { name: 'Lynn', slug: 'lynn', county: 'Essex', state: 'MA', zip: '01901', distance: 27 },
  { name: 'Saugus', slug: 'saugus', county: 'Essex', state: 'MA', zip: '01906', distance: 24 },
  { name: 'Lynnfield', slug: 'lynnfield', county: 'Essex', state: 'MA', zip: '01940', distance: 23 },
  { name: 'Wakefield', slug: 'wakefield', county: 'Essex', state: 'MA', zip: '01880', distance: 22 },
  { name: 'Marblehead', slug: 'marblehead', county: 'Essex', state: 'MA', zip: '01945', distance: 32 },
  { name: 'Swampscott', slug: 'swampscott', county: 'Essex', state: 'MA', zip: '01907', distance: 29 },
  { name: 'Nahant', slug: 'nahant', county: 'Essex', state: 'MA', zip: '01908', distance: 30 },
  { name: 'Beverly', slug: 'beverly', county: 'Essex', state: 'MA', zip: '01915', distance: 32 },
  { name: 'Danvers', slug: 'danvers', county: 'Essex', state: 'MA', zip: '01923', distance: 28 },
  { name: 'Middleton', slug: 'middleton', county: 'Essex', state: 'MA', zip: '01949', distance: 25 },
  { name: 'Topsfield', slug: 'topsfield', county: 'Essex', state: 'MA', zip: '01983', distance: 28 },
  { name: 'Boxford', slug: 'boxford', county: 'Essex', state: 'MA', zip: '01921', distance: 27 },
  { name: 'Georgetown', slug: 'georgetown', county: 'Essex', state: 'MA', zip: '01833', distance: 30 },
  { name: 'Groveland', slug: 'groveland', county: 'Essex', state: 'MA', zip: '01834', distance: 32 },
  { name: 'Newburyport', slug: 'newburyport', county: 'Essex', state: 'MA', zip: '01950', distance: 40 },
  { name: 'Newbury', slug: 'newbury', county: 'Essex', state: 'MA', zip: '01951', distance: 38 },
  { name: 'West Newbury', slug: 'west-newbury', county: 'Essex', state: 'MA', zip: '01985', distance: 36 },
  { name: 'Amesbury', slug: 'amesbury', county: 'Essex', state: 'MA', zip: '01913', distance: 42 },
  { name: 'Salisbury', slug: 'salisbury', county: 'Essex', state: 'MA', zip: '01952', distance: 44 },
  { name: 'Merrimac', slug: 'merrimac', county: 'Essex', state: 'MA', zip: '01860', distance: 38 },
  { name: 'Rowley', slug: 'rowley', county: 'Essex', state: 'MA', zip: '01969', distance: 35 },
  { name: 'Ipswich', slug: 'ipswich', county: 'Essex', state: 'MA', zip: '01938', distance: 36 },
  { name: 'Hamilton', slug: 'hamilton', county: 'Essex', state: 'MA', zip: '01936', distance: 32 },
  { name: 'Wenham', slug: 'wenham', county: 'Essex', state: 'MA', zip: '01984', distance: 30 },
  { name: 'Essex', slug: 'essex-town', county: 'Essex', state: 'MA', zip: '01929', distance: 35 },
  { name: 'Manchester-by-the-Sea', slug: 'manchester-by-the-sea', county: 'Essex', state: 'MA', zip: '01944', distance: 34 },
  { name: 'Gloucester', slug: 'gloucester', county: 'Essex', state: 'MA', zip: '01930', distance: 38 },
  { name: 'Rockport', slug: 'rockport', county: 'Essex', state: 'MA', zip: '01966', distance: 42 },

  // Suffolk County - Expanded
  { name: 'Boston', slug: 'boston', county: 'Suffolk', state: 'MA', zip: '02108', distance: 25 },
  { name: 'Jamaica Plain', slug: 'jamaica-plain', county: 'Suffolk', state: 'MA', zip: '02130', distance: 21 },
  { name: 'West Roxbury', slug: 'west-roxbury', county: 'Suffolk', state: 'MA', zip: '02132', distance: 20 },
  { name: 'Roslindale', slug: 'roslindale', county: 'Suffolk', state: 'MA', zip: '02131', distance: 21 },
  { name: 'Hyde Park', slug: 'hyde-park', county: 'Suffolk', state: 'MA', zip: '02136', distance: 22 },
  { name: 'Dorchester', slug: 'dorchester', county: 'Suffolk', state: 'MA', zip: '02122', distance: 24 },
  { name: 'Mattapan', slug: 'mattapan', county: 'Suffolk', state: 'MA', zip: '02126', distance: 23 },
  { name: 'Roxbury', slug: 'roxbury', county: 'Suffolk', state: 'MA', zip: '02119', distance: 23 },
  { name: 'South Boston', slug: 'south-boston', county: 'Suffolk', state: 'MA', zip: '02127', distance: 26 },
  { name: 'East Boston', slug: 'east-boston', county: 'Suffolk', state: 'MA', zip: '02128', distance: 27 },
  { name: 'Charlestown', slug: 'charlestown', county: 'Suffolk', state: 'MA', zip: '02129', distance: 26 },
  { name: 'Allston', slug: 'allston', county: 'Suffolk', state: 'MA', zip: '02134', distance: 20 },
  { name: 'Brighton', slug: 'brighton', county: 'Suffolk', state: 'MA', zip: '02135', distance: 19 },
  { name: 'Back Bay', slug: 'back-bay', county: 'Suffolk', state: 'MA', zip: '02116', distance: 24 },
  { name: 'Beacon Hill', slug: 'beacon-hill', county: 'Suffolk', state: 'MA', zip: '02108', distance: 25 },
  { name: 'Revere', slug: 'revere', county: 'Suffolk', state: 'MA', zip: '02151', distance: 28 },
  { name: 'Winthrop', slug: 'winthrop', county: 'Suffolk', state: 'MA', zip: '02152', distance: 30 },
  { name: 'Chelsea', slug: 'chelsea', county: 'Suffolk', state: 'MA', zip: '02150', distance: 27 },

  // Plymouth County
  { name: 'Plymouth', slug: 'plymouth', county: 'Plymouth', state: 'MA', zip: '02360', distance: 45 },
  { name: 'Brockton', slug: 'brockton', county: 'Plymouth', state: 'MA', zip: '02301', distance: 32 },
  { name: 'Abington', slug: 'abington', county: 'Plymouth', state: 'MA', zip: '02351', distance: 30 },
  { name: 'Whitman', slug: 'whitman', county: 'Plymouth', state: 'MA', zip: '02382', distance: 32 },
  { name: 'Hanson', slug: 'hanson', county: 'Plymouth', state: 'MA', zip: '02341', distance: 35 },
  { name: 'Halifax', slug: 'halifax', county: 'Plymouth', state: 'MA', zip: '02338', distance: 38 },
  { name: 'Pembroke', slug: 'pembroke', county: 'Plymouth', state: 'MA', zip: '02359', distance: 36 },
  { name: 'Marshfield', slug: 'marshfield', county: 'Plymouth', state: 'MA', zip: '02050', distance: 35 },
  { name: 'Duxbury', slug: 'duxbury', county: 'Plymouth', state: 'MA', zip: '02332', distance: 38 },
  { name: 'Kingston', slug: 'kingston', county: 'Plymouth', state: 'MA', zip: '02364', distance: 42 },
  { name: 'Hingham', slug: 'hingham', county: 'Plymouth', state: 'MA', zip: '02043', distance: 28 },
  { name: 'Cohasset', slug: 'cohasset', county: 'Norfolk', state: 'MA', zip: '02025', distance: 30 },
  { name: 'Scituate', slug: 'scituate', county: 'Plymouth', state: 'MA', zip: '02066', distance: 32 },
  { name: 'Norwell', slug: 'norwell', county: 'Plymouth', state: 'MA', zip: '02061', distance: 30 },
  { name: 'Hanover', slug: 'hanover', county: 'Plymouth', state: 'MA', zip: '02339', distance: 32 },
  { name: 'Rockland', slug: 'rockland', county: 'Plymouth', state: 'MA', zip: '02370', distance: 28 },
  { name: 'Hull', slug: 'hull', county: 'Plymouth', state: 'MA', zip: '02045', distance: 32 },
  { name: 'Weymouth', slug: 'weymouth', county: 'Norfolk', state: 'MA', zip: '02188', distance: 26 },
  { name: 'East Bridgewater', slug: 'east-bridgewater', county: 'Plymouth', state: 'MA', zip: '02333', distance: 33 },
  { name: 'West Bridgewater', slug: 'west-bridgewater', county: 'Plymouth', state: 'MA', zip: '02379', distance: 30 },
  { name: 'Bridgewater', slug: 'bridgewater', county: 'Plymouth', state: 'MA', zip: '02324', distance: 32 },
  { name: 'Middleborough', slug: 'middleborough', county: 'Plymouth', state: 'MA', zip: '02346', distance: 40 },
  { name: 'Lakeville', slug: 'lakeville', county: 'Plymouth', state: 'MA', zip: '02347', distance: 42 },
  { name: 'Carver', slug: 'carver', county: 'Plymouth', state: 'MA', zip: '02330', distance: 45 },
  { name: 'Wareham', slug: 'wareham', county: 'Plymouth', state: 'MA', zip: '02571', distance: 50 },
  { name: 'Marion', slug: 'marion', county: 'Plymouth', state: 'MA', zip: '02738', distance: 52 },
  { name: 'Mattapoisett', slug: 'mattapoisett', county: 'Plymouth', state: 'MA', zip: '02739', distance: 54 },
  { name: 'Rochester', slug: 'rochester', county: 'Plymouth', state: 'MA', zip: '02770', distance: 48 },
  { name: 'Plympton', slug: 'plympton', county: 'Plymouth', state: 'MA', zip: '02367', distance: 40 },

  // Bristol County
  { name: 'Taunton', slug: 'taunton', county: 'Bristol', state: 'MA', zip: '02780', distance: 35 },
  { name: 'Raynham', slug: 'raynham', county: 'Bristol', state: 'MA', zip: '02767', distance: 33 },
  { name: 'Easton', slug: 'easton', county: 'Bristol', state: 'MA', zip: '02356', distance: 28 },
  { name: 'Mansfield', slug: 'mansfield', county: 'Bristol', state: 'MA', zip: '02048', distance: 26 },
  { name: 'Norton', slug: 'norton', county: 'Bristol', state: 'MA', zip: '02766', distance: 28 },
  { name: 'Attleboro', slug: 'attleboro', county: 'Bristol', state: 'MA', zip: '02703', distance: 32 },
  { name: 'North Attleborough', slug: 'north-attleborough', county: 'Bristol', state: 'MA', zip: '02760', distance: 30 },
  { name: 'Rehoboth', slug: 'rehoboth', county: 'Bristol', state: 'MA', zip: '02769', distance: 38 },
  { name: 'Seekonk', slug: 'seekonk', county: 'Bristol', state: 'MA', zip: '02771', distance: 40 },
  { name: 'Swansea', slug: 'swansea', county: 'Bristol', state: 'MA', zip: '02777', distance: 48 },
  { name: 'Somerset', slug: 'somerset', county: 'Bristol', state: 'MA', zip: '02725', distance: 45 },
  { name: 'Fall River', slug: 'fall-river', county: 'Bristol', state: 'MA', zip: '02720', distance: 50 },
  { name: 'Westport', slug: 'westport', county: 'Bristol', state: 'MA', zip: '02790', distance: 55 },
  { name: 'Dartmouth', slug: 'dartmouth', county: 'Bristol', state: 'MA', zip: '02747', distance: 58 },
  { name: 'New Bedford', slug: 'new-bedford', county: 'Bristol', state: 'MA', zip: '02740', distance: 55 },
  { name: 'Fairhaven', slug: 'fairhaven', county: 'Bristol', state: 'MA', zip: '02719', distance: 56 },
  { name: 'Acushnet', slug: 'acushnet', county: 'Bristol', state: 'MA', zip: '02743', distance: 54 },
  { name: 'Freetown', slug: 'freetown', county: 'Bristol', state: 'MA', zip: '02702', distance: 45 },
  { name: 'Berkley', slug: 'berkley', county: 'Bristol', state: 'MA', zip: '02779', distance: 40 },
  { name: 'Dighton', slug: 'dighton', county: 'Bristol', state: 'MA', zip: '02715', distance: 38 },

  // Worcester County Extended (Western MA)
  { name: 'Fitchburg', slug: 'fitchburg', county: 'Worcester', state: 'MA', zip: '01420', distance: 30 },
  { name: 'Leominster', slug: 'leominster', county: 'Worcester', state: 'MA', zip: '01453', distance: 25 },
  { name: 'Lunenburg', slug: 'lunenburg', county: 'Worcester', state: 'MA', zip: '01462', distance: 22 },
  { name: 'Westminster', slug: 'westminster', county: 'Worcester', state: 'MA', zip: '01473', distance: 25 },
  { name: 'Gardner', slug: 'gardner', county: 'Worcester', state: 'MA', zip: '01440', distance: 35 },
  { name: 'Templeton', slug: 'templeton', county: 'Worcester', state: 'MA', zip: '01468', distance: 38 },
  { name: 'Ashburnham', slug: 'ashburnham', county: 'Worcester', state: 'MA', zip: '01430', distance: 35 },
  { name: 'Winchendon', slug: 'winchendon', county: 'Worcester', state: 'MA', zip: '01475', distance: 40 },
  { name: 'Athol', slug: 'athol', county: 'Worcester', state: 'MA', zip: '01331', distance: 45 },
  { name: 'Orange', slug: 'orange', county: 'Franklin', state: 'MA', zip: '01364', distance: 48 },
  { name: 'Petersham', slug: 'petersham', county: 'Worcester', state: 'MA', zip: '01366', distance: 40 },
  { name: 'Barre', slug: 'barre', county: 'Worcester', state: 'MA', zip: '01005', distance: 30 },
  { name: 'Hardwick', slug: 'hardwick', county: 'Worcester', state: 'MA', zip: '01037', distance: 35 },
  { name: 'New Braintree', slug: 'new-braintree', county: 'Worcester', state: 'MA', zip: '01531', distance: 32 },
  { name: 'Oakham', slug: 'oakham', county: 'Worcester', state: 'MA', zip: '01068', distance: 28 },
  { name: 'North Brookfield', slug: 'north-brookfield', county: 'Worcester', state: 'MA', zip: '01535', distance: 30 },
  { name: 'Brookfield', slug: 'brookfield', county: 'Worcester', state: 'MA', zip: '01506', distance: 32 },
  { name: 'East Brookfield', slug: 'east-brookfield', county: 'Worcester', state: 'MA', zip: '01515', distance: 30 },
  { name: 'West Brookfield', slug: 'west-brookfield', county: 'Worcester', state: 'MA', zip: '01585', distance: 35 },
  { name: 'Warren', slug: 'warren', county: 'Worcester', state: 'MA', zip: '01083', distance: 38 },
  { name: 'Sturbridge', slug: 'sturbridge', county: 'Worcester', state: 'MA', zip: '01566', distance: 30 },
  { name: 'Southbridge', slug: 'southbridge', county: 'Worcester', state: 'MA', zip: '01550', distance: 32 },
  { name: 'Dudley', slug: 'dudley', county: 'Worcester', state: 'MA', zip: '01571', distance: 28 },
  { name: 'Thompson', slug: 'thompson', county: 'Worcester', state: 'MA', zip: '01518', distance: 35 },
  { name: 'Woodstock Valley', slug: 'woodstock-valley', county: 'Worcester', state: 'MA', zip: '01519', distance: 38 },
  { name: 'Princeton', slug: 'princeton', county: 'Worcester', state: 'MA', zip: '01541', distance: 20 },
  { name: 'Hubbardston', slug: 'hubbardston', county: 'Worcester', state: 'MA', zip: '01452', distance: 25 },

  // Hampden County
  { name: 'Springfield', slug: 'springfield', county: 'Hampden', state: 'MA', zip: '01101', distance: 55 },
  { name: 'Chicopee', slug: 'chicopee', county: 'Hampden', state: 'MA', zip: '01013', distance: 52 },
  { name: 'Holyoke', slug: 'holyoke', county: 'Hampden', state: 'MA', zip: '01040', distance: 55 },
  { name: 'Westfield', slug: 'westfield', county: 'Hampden', state: 'MA', zip: '01085', distance: 60 },
  { name: 'West Springfield', slug: 'west-springfield', county: 'Hampden', state: 'MA', zip: '01089', distance: 58 },
  { name: 'Agawam', slug: 'agawam', county: 'Hampden', state: 'MA', zip: '01001', distance: 60 },
  { name: 'Longmeadow', slug: 'longmeadow', county: 'Hampden', state: 'MA', zip: '01106', distance: 58 },
  { name: 'East Longmeadow', slug: 'east-longmeadow', county: 'Hampden', state: 'MA', zip: '01028', distance: 55 },
  { name: 'Wilbraham', slug: 'wilbraham', county: 'Hampden', state: 'MA', zip: '01095', distance: 52 },
  { name: 'Hampden', slug: 'hampden-town', county: 'Hampden', state: 'MA', zip: '01036', distance: 50 },
  { name: 'Monson', slug: 'monson', county: 'Hampden', state: 'MA', zip: '01057', distance: 45 },
  { name: 'Palmer', slug: 'palmer', county: 'Hampden', state: 'MA', zip: '01069', distance: 48 },
  { name: 'Ludlow', slug: 'ludlow', county: 'Hampden', state: 'MA', zip: '01056', distance: 50 },
  { name: 'Brimfield', slug: 'brimfield', county: 'Hampden', state: 'MA', zip: '01010', distance: 40 },
  { name: 'Wales', slug: 'wales', county: 'Hampden', state: 'MA', zip: '01081', distance: 42 },
  { name: 'Holland', slug: 'holland', county: 'Hampden', state: 'MA', zip: '01521', distance: 38 },

  // Hampshire County
  { name: 'Northampton', slug: 'northampton', county: 'Hampshire', state: 'MA', zip: '01060', distance: 60 },
  { name: 'Easthampton', slug: 'easthampton', county: 'Hampshire', state: 'MA', zip: '01027', distance: 58 },
  { name: 'South Hadley', slug: 'south-hadley', county: 'Hampshire', state: 'MA', zip: '01075', distance: 55 },
  { name: 'Amherst', slug: 'amherst', county: 'Hampshire', state: 'MA', zip: '01002', distance: 58 },
  { name: 'Hadley', slug: 'hadley', county: 'Hampshire', state: 'MA', zip: '01035', distance: 60 },
  { name: 'Belchertown', slug: 'belchertown', county: 'Hampshire', state: 'MA', zip: '01007', distance: 50 },
  { name: 'Ware', slug: 'ware', county: 'Hampshire', state: 'MA', zip: '01082', distance: 45 },
  { name: 'Granby', slug: 'granby', county: 'Hampshire', state: 'MA', zip: '01033', distance: 52 },

  // Middlesex County Extended (Northern)
  { name: 'Lowell', slug: 'lowell', county: 'Middlesex', state: 'MA', zip: '01852', distance: 28 },
  { name: 'Dracut', slug: 'dracut', county: 'Middlesex', state: 'MA', zip: '01826', distance: 30 },
  { name: 'Tyngsborough', slug: 'tyngsborough', county: 'Middlesex', state: 'MA', zip: '01879', distance: 28 },
  { name: 'Pepperell', slug: 'pepperell', county: 'Middlesex', state: 'MA', zip: '01463', distance: 25 },
  { name: 'Townsend', slug: 'townsend', county: 'Middlesex', state: 'MA', zip: '01469', distance: 28 },
  { name: 'Ashby', slug: 'ashby', county: 'Middlesex', state: 'MA', zip: '01431', distance: 30 },
  { name: 'Shirley', slug: 'shirley', county: 'Middlesex', state: 'MA', zip: '01464', distance: 20 },
  { name: 'Stoneham', slug: 'stoneham', county: 'Middlesex', state: 'MA', zip: '02180', distance: 22 },
  { name: 'Melrose', slug: 'melrose', county: 'Middlesex', state: 'MA', zip: '02176', distance: 23 },
  { name: 'Malden', slug: 'malden', county: 'Middlesex', state: 'MA', zip: '02148', distance: 24 },
  { name: 'Everett', slug: 'everett', county: 'Middlesex', state: 'MA', zip: '02149', distance: 25 },
  // Norfolk County Extended
  { name: 'Stoughton', slug: 'stoughton', county: 'Norfolk', state: 'MA', zip: '02072', distance: 25 },
  { name: 'Avon', slug: 'avon', county: 'Norfolk', state: 'MA', zip: '02322', distance: 26 },
  { name: 'Norfolk', slug: 'norfolk-town', county: 'Norfolk', state: 'MA', zip: '02056', distance: 20 },
  { name: 'Walpole', slug: 'walpole', county: 'Norfolk', state: 'MA', zip: '02081', distance: 22 },
  { name: 'Wrentham', slug: 'wrentham', county: 'Norfolk', state: 'MA', zip: '02093', distance: 24 },
  { name: 'Plainville', slug: 'plainville', county: 'Norfolk', state: 'MA', zip: '02762', distance: 26 },

  // Barnstable County (Cape Cod)
  { name: 'Barnstable', slug: 'barnstable', county: 'Barnstable', state: 'MA', zip: '02630', distance: 65 },
  { name: 'Hyannis', slug: 'hyannis', county: 'Barnstable', state: 'MA', zip: '02601', distance: 68 },
  { name: 'Yarmouth', slug: 'yarmouth', county: 'Barnstable', state: 'MA', zip: '02664', distance: 70 },
  { name: 'Dennis', slug: 'dennis', county: 'Barnstable', state: 'MA', zip: '02638', distance: 72 },
  { name: 'Harwich', slug: 'harwich', county: 'Barnstable', state: 'MA', zip: '02645', distance: 75 },
  { name: 'Chatham', slug: 'chatham', county: 'Barnstable', state: 'MA', zip: '02633', distance: 80 },
  { name: 'Orleans', slug: 'orleans', county: 'Barnstable', state: 'MA', zip: '02653', distance: 82 },
  { name: 'Brewster', slug: 'brewster', county: 'Barnstable', state: 'MA', zip: '02631', distance: 78 },
  { name: 'Eastham', slug: 'eastham', county: 'Barnstable', state: 'MA', zip: '02642', distance: 85 },
  { name: 'Wellfleet', slug: 'wellfleet', county: 'Barnstable', state: 'MA', zip: '02667', distance: 88 },
  { name: 'Truro', slug: 'truro', county: 'Barnstable', state: 'MA', zip: '02666', distance: 92 },
  { name: 'Provincetown', slug: 'provincetown', county: 'Barnstable', state: 'MA', zip: '02657', distance: 95 },
  { name: 'Sandwich', slug: 'sandwich', county: 'Barnstable', state: 'MA', zip: '02563', distance: 58 },
  { name: 'Bourne', slug: 'bourne', county: 'Barnstable', state: 'MA', zip: '02532', distance: 55 },
  { name: 'Falmouth', slug: 'falmouth', county: 'Barnstable', state: 'MA', zip: '02540', distance: 62 },
  { name: 'Mashpee', slug: 'mashpee', county: 'Barnstable', state: 'MA', zip: '02649', distance: 65 },

  // Dukes County (Martha's Vineyard)
  { name: 'Edgartown', slug: 'edgartown', county: 'Dukes', state: 'MA', zip: '02539', distance: 80 },
  { name: 'Oak Bluffs', slug: 'oak-bluffs', county: 'Dukes', state: 'MA', zip: '02557', distance: 78 },
  { name: 'Vineyard Haven', slug: 'vineyard-haven', county: 'Dukes', state: 'MA', zip: '02568', distance: 75 },
  { name: 'West Tisbury', slug: 'west-tisbury', county: 'Dukes', state: 'MA', zip: '02575', distance: 82 },
  { name: 'Chilmark', slug: 'chilmark', county: 'Dukes', state: 'MA', zip: '02535', distance: 85 },
  { name: 'Aquinnah', slug: 'aquinnah', county: 'Dukes', state: 'MA', zip: '02535', distance: 88 },

  // Nantucket County
  { name: 'Nantucket', slug: 'nantucket', county: 'Nantucket', state: 'MA', zip: '02554', distance: 100 },

  // Franklin County (Western MA)
  { name: 'Greenfield', slug: 'greenfield', county: 'Franklin', state: 'MA', zip: '01301', distance: 65 },
  { name: 'Deerfield', slug: 'deerfield', county: 'Franklin', state: 'MA', zip: '01342', distance: 68 },
  { name: 'Montague', slug: 'montague', county: 'Franklin', state: 'MA', zip: '01351', distance: 62 },
  { name: 'Turners Falls', slug: 'turners-falls', county: 'Franklin', state: 'MA', zip: '01376', distance: 60 },
  { name: 'Shelburne Falls', slug: 'shelburne-falls', county: 'Franklin', state: 'MA', zip: '01370', distance: 72 },
  { name: 'Conway', slug: 'conway', county: 'Franklin', state: 'MA', zip: '01341', distance: 70 },
  { name: 'Sunderland', slug: 'sunderland', county: 'Franklin', state: 'MA', zip: '01375', distance: 65 },
  { name: 'Leverett', slug: 'leverett', county: 'Franklin', state: 'MA', zip: '01054', distance: 60 },
  { name: 'Shutesbury', slug: 'shutesbury', county: 'Franklin', state: 'MA', zip: '01072', distance: 55 },
  { name: 'New Salem', slug: 'new-salem', county: 'Franklin', state: 'MA', zip: '01355', distance: 50 },
  { name: 'Wendell', slug: 'wendell', county: 'Franklin', state: 'MA', zip: '01379', distance: 52 },
  { name: 'Erving', slug: 'erving', county: 'Franklin', state: 'MA', zip: '01344', distance: 55 },
  { name: 'Northfield', slug: 'northfield', county: 'Franklin', state: 'MA', zip: '01360', distance: 70 },
  { name: 'Bernardston', slug: 'bernardston', county: 'Franklin', state: 'MA', zip: '01337', distance: 72 },
  { name: 'Gill', slug: 'gill', county: 'Franklin', state: 'MA', zip: '01354', distance: 65 },
  { name: 'Whately', slug: 'whately', county: 'Franklin', state: 'MA', zip: '01093', distance: 68 },
  { name: 'Ashfield', slug: 'ashfield', county: 'Franklin', state: 'MA', zip: '01330', distance: 75 },
  { name: 'Colrain', slug: 'colrain', county: 'Franklin', state: 'MA', zip: '01340', distance: 78 },

  // Berkshire County (Western MA)
  { name: 'Pittsfield', slug: 'pittsfield', county: 'Berkshire', state: 'MA', zip: '01201', distance: 95 },
  { name: 'North Adams', slug: 'north-adams', county: 'Berkshire', state: 'MA', zip: '01247', distance: 100 },
  { name: 'Adams', slug: 'adams', county: 'Berkshire', state: 'MA', zip: '01220', distance: 98 },
  { name: 'Williamstown', slug: 'williamstown', county: 'Berkshire', state: 'MA', zip: '01267', distance: 105 },
  { name: 'Great Barrington', slug: 'great-barrington', county: 'Berkshire', state: 'MA', zip: '01230', distance: 100 },
  { name: 'Stockbridge', slug: 'stockbridge', county: 'Berkshire', state: 'MA', zip: '01262', distance: 95 },
  { name: 'Lee', slug: 'lee', county: 'Berkshire', state: 'MA', zip: '01238', distance: 90 },
  { name: 'Lenox', slug: 'lenox', county: 'Berkshire', state: 'MA', zip: '01240', distance: 92 },
  { name: 'Dalton', slug: 'dalton', county: 'Berkshire', state: 'MA', zip: '01226', distance: 95 },
  { name: 'Lanesborough', slug: 'lanesborough', county: 'Berkshire', state: 'MA', zip: '01237', distance: 98 },
  { name: 'Cheshire', slug: 'cheshire', county: 'Berkshire', state: 'MA', zip: '01225', distance: 96 },
  { name: 'Hinsdale', slug: 'hinsdale', county: 'Berkshire', state: 'MA', zip: '01235', distance: 88 },
  { name: 'Peru', slug: 'peru', county: 'Berkshire', state: 'MA', zip: '01235', distance: 85 },
  { name: 'Becket', slug: 'becket', county: 'Berkshire', state: 'MA', zip: '01223', distance: 80 },
  { name: 'Otis', slug: 'otis', county: 'Berkshire', state: 'MA', zip: '01253', distance: 82 },
  { name: 'Sandisfield', slug: 'sandisfield', county: 'Berkshire', state: 'MA', zip: '01255', distance: 85 },
  { name: 'Sheffield', slug: 'sheffield', county: 'Berkshire', state: 'MA', zip: '01257', distance: 102 },
  { name: 'Egremont', slug: 'egremont', county: 'Berkshire', state: 'MA', zip: '01230', distance: 100 },

  // Additional Hampshire County
  { name: 'Huntington', slug: 'huntington', county: 'Hampshire', state: 'MA', zip: '01050', distance: 60 },
  { name: 'Williamsburg', slug: 'williamsburg', county: 'Hampshire', state: 'MA', zip: '01096', distance: 62 },
  { name: 'Goshen', slug: 'goshen', county: 'Hampshire', state: 'MA', zip: '01032', distance: 65 },
  { name: 'Chesterfield', slug: 'chesterfield', county: 'Hampshire', state: 'MA', zip: '01012', distance: 68 },
  { name: 'Cummington', slug: 'cummington', county: 'Hampshire', state: 'MA', zip: '01026', distance: 70 },
  { name: 'Worthington', slug: 'worthington', county: 'Hampshire', state: 'MA', zip: '01098', distance: 72 },
  { name: 'Pelham', slug: 'pelham', county: 'Hampshire', state: 'MA', zip: '01002', distance: 55 },
  { name: 'Hatfield', slug: 'hatfield', county: 'Hampshire', state: 'MA', zip: '01038', distance: 62 },
  { name: 'Southampton', slug: 'southampton', county: 'Hampshire', state: 'MA', zip: '01073', distance: 58 },
  { name: 'Westhampton', slug: 'westhampton', county: 'Hampshire', state: 'MA', zip: '01027', distance: 60 },

  // Additional Hampden County
  { name: 'Russell', slug: 'russell', county: 'Hampden', state: 'MA', zip: '01071', distance: 65 },
  { name: 'Blandford', slug: 'blandford', county: 'Hampden', state: 'MA', zip: '01008', distance: 70 },
  { name: 'Chester', slug: 'chester', county: 'Hampden', state: 'MA', zip: '01011', distance: 68 },
  { name: 'Montgomery', slug: 'montgomery', county: 'Hampden', state: 'MA', zip: '01050', distance: 62 },
  { name: 'Granville', slug: 'granville', county: 'Hampden', state: 'MA', zip: '01034', distance: 68 },
  { name: 'Tolland', slug: 'tolland', county: 'Hampden', state: 'MA', zip: '01034', distance: 70 },

  // Additional Worcester County
  { name: 'Royalston', slug: 'royalston', county: 'Worcester', state: 'MA', zip: '01368', distance: 48 },
  { name: 'Phillipston', slug: 'phillipston', county: 'Worcester', state: 'MA', zip: '01331', distance: 42 },
];

export function getCityBySlug(slug: string): City | undefined {
  return cities.find(city => city.slug === slug);
}

export function getCitiesByCounty(county: string): City[] {
  return cities.filter(city => city.county === county);
}

export function getCitiesByDistance(maxMiles: number): City[] {
  return cities.filter(city => city.distance <= maxMiles);
}

export function getNearbyCities(slug: string, limit = 6): City[] {
  const city = getCityBySlug(slug);
  if (!city) return [];
  return cities
    .filter(c => c.slug !== slug)
    .sort((a, b) => Math.abs(a.distance - city.distance) - Math.abs(b.distance - city.distance))
    .slice(0, limit);
}

export function getAllCitySlugs(): string[] {
  return cities.map(city => city.slug);
}
